FROM node:20-alpine as build
WORKDIR /app
COPY package*.json ./
COPY client/package*.json ./client/
RUN npm install --workspace=client
COPY client ./client
RUN npm run build --workspace=client

FROM nginx:1.27-alpine
COPY --from=build /app/client/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
